### ISSUE TITLE
Add a publication date on articles.

### ISSUE THREAD

**Issue by SuzeShardlow** [redis-developer/redis-developer#151]
We especially need these on blog posts so it's clear when they were written.

**Comment by simonprickett** [comment]
@SuzeShardlow @ajeetraina I looked into this and believe we can do this by tweaking the doc item template but we also need to change the GitHub actions job to deploy by doing a deep clone of the repo - see link here for details:

https://github.com/facebook/docusaurus/issues/2798#issuecomment-636602951

I think this is fine, but not something we can test locally, so maybe I'll try this out of hours sometime.

We're also need to turn on `showLastUpdateTime` for the docs plugin (https://docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs)

I'm happy to take this on and adjust the template so the last updated appears near the author section.

**Comment by SuzeShardlow** [comment]
Happy to assign this to you.  Go for it :)
