### ISSUE TITLE
The PooledJedisConnectionProvider not import in [using java doc]

### ISSUE THREAD

**Issue by zishinan** [redis-developer/redis-developer#242]
The PooledJedisConnectionProvider class not import in [using java doc](https://developer.redis.com/howtos/redisjson/using-java)

show the code like this:
PooledJedisConnectionProvider provider = new PooledJedisConnectionProvider(config);

but i donot know PooledJedisConnectionProvider class how to import, it is not in Jedis maven lib

**Comment by HangMy** [comment]
PooledJedisConnectionProvider ，同上求助这个类找不到。 引入的是4.0.0版本和4.0.1版本都不行

**Comment by zishinan** [comment]
PooledConnectionProvider provider = new PooledConnectionProvider(config, clientConfig);
        // FIXME: 2022/1/6  here can not import
//        PooledJedisConnectionProvider provider = new PooledJedisConnectionProvider(config);

        JedisSocketFactory jedisSocketFactory = new DefaultJedisSocketFactory(config, clientConfig);
        UnifiedJedis client = new UnifiedJedis(provider);
//        Player player = new Player("ouyang","ouayngxi");
//        client.jsonSet(Player.class.getSimpleName() + ":" + 1, player);


        client.set("testouyang", "jljflasjdlfkls");
        System.out.println(client.get("testouyang"));
        Student maya = new Student("Maya", "Jayavant");
        // FIXME: 2022/1/6 here make error： expected value at line 1 column 1
        client.jsonSet("student:111", maya);
