### ISSUE TITLE
Author front matter field needs a fix

### ISSUE THREAD

**Issue by ajeetraina** [redis-developer/redis-developer#265]
I noticed that author front matter field is not working at all

@simonprickett any idea?

**Comment by simonprickett** [comment]
Looks like there's no HTML for the author area in the final rendered page on the live site.  Will take a look when I get a moment.

**Comment by simonprickett** [comment]
@ajeetraina looks like this file that used to render the documents and include the author information isn't part of the project anymore... was the theme upgraded or changed? https://github.com/redis-developer/redis-developer.github.io/blob/8fb7af4263c343c55d8df98999783f0f48e8becb/src/theme/DocItem/index.tsx

**Comment by ajeetraina** [comment]
@simonprickett No. I don't think there was any PR that changes this. But I could see that author section is working fine now.
