### ISSUE TITLE
Error in documentation: Node.js, Nginx, Redis and Docker

### ISSUE THREAD

**Issue by anaselhajjaji** [redis-developer/redis-developer#288]
https://github.com/redis-developer/redis-developer.github.io/blob/master/docs/create/docker/nodejs-nginx-redis/index-nodejs-nginx-redis.mdx#file-nginxnginxconf

The nginx conf is not correct:
![image](https://user-images.githubusercontent.com/3309485/157361636-bd158382-06f3-4172-9d6d-962689ffa602.png)

**Comment by ajeetraina** [comment]
@anaselhajjaji Thanks for reporting the issue.
I have raised PR to get it fixed.
