### ISSUE TITLE
Step 4 on the Redis Bloom guide has a link that's a 404

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redis-developer#297]
In step 4, the link for connecting to the database using RedisInsight is a 404.  Affected page https://developer.redis.com/howtos/redisbloom/

**Comment by ajeetraina** [comment]
@simonprickett I have re-worked this guide to include Redis Stack and hence that fixes the overall tutorials.

**Comment by simonprickett** [comment]
Closing as this is now fixed, thanks @ajeetraina
