### ISSUE TITLE
Add Michael's preferred social media link to his author profile.

### ISSUE THREAD

**Issue by SuzeShardlow** [redis-developer/redis-developer#405]
@iMichaelOwolabi, I've added you as an author on your profile page.  See here:

https://developer.redis.com/redis-insiders/michael-owolabi/

You have the option of having a link under your name in the author section (like mine has).

Feel free to add one of your social links to your author profile here (see lines 148-151):

https://github.com/redis-developer/redis-developer.github.io/blob/master/docusaurus.config.js

I would have added it for you, but I wasn't sure if you preferred to link to LinkedIn or Twitter.

Once you have done that, please open a PR and add me as a reviewer and I will approve and merge it.

Thanks!

**Comment by iMichaelOwolabi** [comment]
@SuzeShardlow , I've created the PR to update the link but couldn't update the reviewer section. Not sure why that is but here is the PR [link](https://github.com/redis-developer/redis-developer.github.io/pull/406)

**Comment by SuzeShardlow** [comment]
Thanks Michael!  Not sure why you weren't able to do that, but I have approved and merged this in :)

**Comment by SuzeShardlow** [comment]
Closed by #406.
