### ISSUE TITLE
Link to Python JSON tutorial is a  404

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redis-developer#98]
Link for "Storing JSON document in Redis using Python" is broken here https://developer.redis.com/develop/python/#references

This should also say "Storing JSON documents in Redis using Python". - documents plural

**Comment by ajeetraina** [comment]
Thanks @simonprickett for reporting this. I have fixed the link.

**Comment by simonprickett** [comment]
Verifying this was fixed in https://github.com/redis-developer/redis-developer.github.io/commit/34248655a1665e25da256f8f5bb297b1675ada6d, closing issue.
